version: "3.8"

services:

  website:
    image: ${DOCKER_REGISTRY}/chieldemmer:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    ports:
      - target: 80       
        published: 80    
        protocol: tcp
        mode: host
